version: '3.3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=auth
    volumes:
      - ./data:/data
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=advocacia_mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: